/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as ApiOrdersRouteImport } from './routes/api.orders'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as ApiAuthSyncRouteImport } from './routes/api.auth.sync'
import { Route as ApiAdminOrdersRouteImport } from './routes/api.admin.orders'
import { Route as ApiAccountOrdersRouteImport } from './routes/api.account.orders'
import { Route as ApiAdminOrdersIdStatusRouteImport } from './routes/api.admin.orders.$id.status'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ShopRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSyncRoute = ApiAuthSyncRouteImport.update({
  id: '/api/auth/sync',
  path: '/api/auth/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersRoute = ApiAdminOrdersRouteImport.update({
  id: '/api/admin/orders',
  path: '/api/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountOrdersRoute = ApiAccountOrdersRouteImport.update({
  id: '/api/account/orders',
  path: '/api/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersIdStatusRoute = ApiAdminOrdersIdStatusRouteImport.update({
  id: '/$id/status',
  path: '/$id/status',
  getParentRoute: () => ApiAdminOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/account/orders': typeof AccountOrdersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/api/orders': typeof ApiOrdersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/shop/': typeof ShopIndexRoute
  '/api/account/orders': typeof ApiAccountOrdersRoute
  '/api/admin/orders': typeof ApiAdminOrdersRouteWithChildren
  '/api/auth/sync': typeof ApiAuthSyncRoute
  '/api/admin/orders/$id/status': typeof ApiAdminOrdersIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/api/orders': typeof ApiOrdersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/shop': typeof ShopIndexRoute
  '/api/account/orders': typeof ApiAccountOrdersRoute
  '/api/admin/orders': typeof ApiAdminOrdersRouteWithChildren
  '/api/auth/sync': typeof ApiAuthSyncRoute
  '/api/admin/orders/$id/status': typeof ApiAdminOrdersIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/account/orders': typeof AccountOrdersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/api/orders': typeof ApiOrdersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/shop/': typeof ShopIndexRoute
  '/api/account/orders': typeof ApiAccountOrdersRoute
  '/api/admin/orders': typeof ApiAdminOrdersRouteWithChildren
  '/api/auth/sync': typeof ApiAuthSyncRoute
  '/api/admin/orders/$id/status': typeof ApiAdminOrdersIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/order-success'
    | '/orders'
    | '/settings'
    | '/shop'
    | '/account/orders'
    | '/admin/orders'
    | '/api/orders'
    | '/auth/login'
    | '/auth/signup'
    | '/products/$slug'
    | '/shop/$category'
    | '/shop/'
    | '/api/account/orders'
    | '/api/admin/orders'
    | '/api/auth/sync'
    | '/api/admin/orders/$id/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/order-success'
    | '/orders'
    | '/settings'
    | '/account/orders'
    | '/admin/orders'
    | '/api/orders'
    | '/auth/login'
    | '/auth/signup'
    | '/products/$slug'
    | '/shop/$category'
    | '/shop'
    | '/api/account/orders'
    | '/api/admin/orders'
    | '/api/auth/sync'
    | '/api/admin/orders/$id/status'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/order-success'
    | '/orders'
    | '/settings'
    | '/shop'
    | '/account/orders'
    | '/admin/orders'
    | '/api/orders'
    | '/auth/login'
    | '/auth/signup'
    | '/products/$slug'
    | '/shop/$category'
    | '/shop/'
    | '/api/account/orders'
    | '/api/admin/orders'
    | '/api/auth/sync'
    | '/api/admin/orders/$id/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  OrdersRoute: typeof OrdersRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRouteWithChildren
  AccountOrdersRoute: typeof AccountOrdersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiAccountOrdersRoute: typeof ApiAccountOrdersRoute
  ApiAdminOrdersRoute: typeof ApiAdminOrdersRouteWithChildren
  ApiAuthSyncRoute: typeof ApiAuthSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof ShopRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sync': {
      id: '/api/auth/sync'
      path: '/api/auth/sync'
      fullPath: '/api/auth/sync'
      preLoaderRoute: typeof ApiAuthSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders': {
      id: '/api/admin/orders'
      path: '/api/admin/orders'
      fullPath: '/api/admin/orders'
      preLoaderRoute: typeof ApiAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/orders': {
      id: '/api/account/orders'
      path: '/api/account/orders'
      fullPath: '/api/account/orders'
      preLoaderRoute: typeof ApiAccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/$id/status': {
      id: '/api/admin/orders/$id/status'
      path: '/$id/status'
      fullPath: '/api/admin/orders/$id/status'
      preLoaderRoute: typeof ApiAdminOrdersIdStatusRouteImport
      parentRoute: typeof ApiAdminOrdersRoute
    }
  }
}

interface ShopRouteChildren {
  ShopCategoryRoute: typeof ShopCategoryRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCategoryRoute: ShopCategoryRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface ApiAdminOrdersRouteChildren {
  ApiAdminOrdersIdStatusRoute: typeof ApiAdminOrdersIdStatusRoute
}

const ApiAdminOrdersRouteChildren: ApiAdminOrdersRouteChildren = {
  ApiAdminOrdersIdStatusRoute: ApiAdminOrdersIdStatusRoute,
}

const ApiAdminOrdersRouteWithChildren = ApiAdminOrdersRoute._addFileChildren(
  ApiAdminOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  OrdersRoute: OrdersRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRouteWithChildren,
  AccountOrdersRoute: AccountOrdersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiAccountOrdersRoute: ApiAccountOrdersRoute,
  ApiAdminOrdersRoute: ApiAdminOrdersRouteWithChildren,
  ApiAuthSyncRoute: ApiAuthSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
